version: '3'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./result:/app/result  # Le volume devrait être mappé au répertoire approprié dans le conteneur
    restart: always